package com.legalrag.user;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity mapping to the 'users' table.
 *
 * Schema (already created on Neon via blueprint SQL):
 *
 *   CREATE TABLE users (
 *       id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *       email         VARCHAR(255) UNIQUE NOT NULL,
 *       password_hash VARCHAR(255) NOT NULL,
 *       full_name     VARCHAR(255),
 *       created_at    TIMESTAMP DEFAULT NOW()
 *   );
 *
 * Notes:
 * - UUID primary key generated by the database (gen_random_uuid()),
 *   not by Hibernate — so we use GenerationType.NONE and rely on
 *   @PrePersist to assign it in Java when a new entity is created
 *   without an id (defensive fallback).
 *
 * - password_hash stores the BCrypt hash. The plain password is never
 *   stored anywhere in this system.
 *
 * - This entity does NOT implement UserDetails directly — we keep JPA
 *   concerns separate from Spring Security concerns. UserDetailsServiceImpl
 *   wraps this entity into a Spring Security UserDetails object.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    @Id
    @Column(name = "id", updatable = false, nullable = false,
            columnDefinition = "uuid")
    private UUID id;

    @Column(name = "email", unique = true, nullable = false, length = 255)
    private String email;

    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "full_name", length = 255)
    private String fullName;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    /**
     * Assign a UUID before the entity is first persisted if one was not
     * provided by the caller. The database will also generate one via
     * DEFAULT, but this ensures the Java object is consistent after save
     * without needing a separate SELECT.
     */
    @PrePersist
    public void assignId() {
        if (this.id == null) {
            this.id = UUID.randomUUID();
        }
    }
}